version: '3'
services:
  db:
    image: mongo:7.0.0
    container_name: db
    
    ports:
     - "4000:27017"
    restart: always

  video-streaming:
    image: video-streaming
    build:
      context: ./streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4000:80"
    volumes:
      - /mnt/media/movies:/media/movies:ro # Read-only access to your movie library
      - /mnt/media/tvshows:/media/tvshows:ro # Read-only access to your TV show library
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - MEDIA_BASE_DIR_MOVIES=/media/movies # Explicitly set this if desired
      - MEDIA_BASE_DIR_TVSHOWS=/media/tvshows # Explicitly set this if desired
    restart: "no"