version: '3'
services:

  video-streaming:
    image: video-streaming
    build: 
      context: ./streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4000:80"
    volumes:
      - /mnt/media/movies:/media/movies:ro # Read-only access to your movie library
      - /mnt/media/tvshows:/media/tvshows:ro # Read-only access to your TV show library
    environment:
      - PORT=80
    restart: "no"
