version: '3'
services:
  db:
    image: mongo:7.0.0
    container_name: db
    ports:
      - "4002:27017"
    command: mongod --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  video-streaming:
    image: video-streaming
    build:
      context: ./streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4000:80"
    volumes:
      - /mnt/media/movies:/media/movies:ro
      - /mnt/media/tvshows:/media/tvshows:ro
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - MEDIA_BASE_DIR_MOVIES=/media/movies
      - MEDIA_BASE_DIR_TVSHOWS=/media/tvshows
    restart: "no"
    depends_on:
      db:
        condition: service_healthy # Wait until the db service is healthy