/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

/**
 * Use the `mockitoAgent` configuration to add the Mockito agent as a Java agent.
 */
val mockitoAgent = configurations.create("mockitoAgent")

plugins {
    id("java")
    id("org.openjfx.javafxplugin") version "0.1.0"
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Jackson to serialize and deserialize JSON data.
    // https://mvnrepository.com/artifact/tools.jackson.core/jackson-databind
    implementation("tools.jackson.core:jackson-databind:3.0.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.20.0")

    // Use Mockito for mocking objects in tests.
    testImplementation("org.mockito:mockito-core:5.+")
    testImplementation("org.mockito:mockito-junit-jupiter:5.16.0")
    mockitoAgent("org.mockito:mockito-core:5.+") { isTransitive = false }

    // https://mvnrepository.com/artifact/org.kordamp.ikonli/ikonli-javafx
    implementation("org.kordamp.ikonli:ikonli-javafx:12.4.0")
    // https://mvnrepository.com/artifact/org.kordamp.ikonli/ikonli-bootstrapicons-pack
    implementation("org.kordamp.ikonli:ikonli-bootstrapicons-pack:12.4.0")
    implementation("org.kordamp.ikonli:ikonli-fontawesome6-pack:12.4.0")

    testImplementation("org.junit.jupiter:junit-jupiter:5+")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "ch.zhaw.it.pm3.occupi.Occupi"
}

tasks {
    test {
        jvmArgs("-javaagent:${mockitoAgent.asPath}")
    }

}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

javafx {
    version = "23.0.1"
    modules("javafx.controls", "javafx.fxml")
}

